import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/page";
import Footer from "@/components/Footer/page";
import ImageSlider from "@/components/CorosuleSlider/page";
import img1 from '@/../public/Images/img1.jpg'
import img2 from '@/../public/Images/img2.jpg'
import img3 from '@/../public/Images/img3.jpg'
import CartButton from "@/components/CartButton/page";
import SideBar from "@/components/CartItems/page";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Ecommerce Website",
  description: "Generated by create next app",
};

const sliderImages = [ img1, img2, img3 ];


export default async function MainLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (

    <>

      <Header />
      
      <ImageSlider images={sliderImages}/>
  
      {children}

      <Footer />
      
      <CartButton />
      
      <SideBar />  

    </>
  );
}


